<?
$faq=array("product"=>array(),"technical_amp_safety"=>array(),"guarantee"=>array(),"payment_amp_delivery"=>array(),"miscellaneous"=>array());
$faq['product'][]=array("Why are Lafuma products more expensive than other products?","Lafuma products have been produced in France for the last 50 years.  The experience and expertise, top quality materials and uncompromising attention to detail make Lafuma unique in the market place.  Lafuma products feature patented designs that others may often attempt to imitate but are never able to duplicate in the same quality.  Ecological concerns guide Lafuma in their production and logistics.  For more details, please click <a href='index.php?p=whylafuma'>here</a>.");
$faq['product'][]=array("What is the difference between an XL chair and a regular chair? (For example; Futura XL Recliner & Futura Recliner).","As the name might suggest, the only difference between the chairs will be the size.  An XL chair is extra large, so it is wider, taller &amp; longer then the standard size chair.  However, the user weight limits on a standard and XL chair will be the same.  We recommend XL chairs to those who are over 6&acute; tall.");
$faq['product'][]=array("What is the difference between a Futura and an R Clip chair?","There are 3 differences between these two chairs.  The Futura can be reclined by using a mechanism in the arms.  The R Clip has a simpler arm system, so therefore can only be reclined by shifting your body weight.  The R Clip&acute;s canvas is not clipped as high as the Futura canvas, meaning that the R Clip has a slightly more hammock style feel.  Finally, the R Clip does not come with a plastic foot bar protector, whereas the Futura does.");
$faq['product'][]=array("What is the difference between an RSXA and a RSX?","The frame, lacing cords and mechanisms on both chairs are exactly the same in both chairs; the only difference is the canvas.  The RSX has a cushioned padded fabric, whereas the RSXA have a batyline &#34;mesh&#34; type material.  For more details on fabrics, please click <a href='index.php?p=frames_fabrics'>here</a>.");
$faq['product'][]=array("What is the difference between the Futura &amp; RSX chairs?","The RSXA chairs have their canvasses suspended with lacing cords, which gives them a hammock style effect which some people prefer.  However, the lacing cords do need to be replaced periodically.  The Futura chairs are suspended by clips, which hold them tight.  Some people prefer the hammock style feel; others prefer the harder, tighter seat.  The clips on the Futura are also covered by a 3 year guarantee.  The Futura chairs also have a mechanism in the arm which means that you can recline the chair by just pulling back on the arms.  To recline the RSX chairs you need to shift your body weight.  Therefore, the Futura&acute;s arm reclining mechanism is better suited for those of less mobility.");
$faq['product'][]=array("Will the Lafuma carry bag fit other chairs apart from the RSX?","Yes, all other Lafuma chairs will fit in the carry bag; this includes larger chairs like the Futura XL.  We recommend that that chairs are stored in these bags during the winter to help further protect them from the elements.  Please note that the zip area of the bag is not waterproof.");


$faq['technical_amp_safety'][]=array("I need to purchase a spare part, where should I go?","Most of the Lafuma spare parts can be purchased online by clicking <a href='index.php?p=products&amp;cat=9&amp;catname=lafuma_spares'>here</a>. If you are unable to find the spare part you require, please email <a href='mailto:support@lafuma.co.uk'>support@lafuma.co.uk</a> or click on the <a href='index.php?p=contact'>Contact Us</a>  page.   Make sure you include an image of both the spare part and the chair, as well the rough age of the Lafuma product (spare parts change depending on the age of the product), and your contact details. We will then contact you with availability and price. We do hold a large selection of spares for the Lafuma chairs, so will more than likely be able to help.");
$faq['technical_amp_safety'][]=array("Do the RSX or Futura chairs lock into position?","No, the chairs do not lock into position.  They have a stabilising mechanism under the arms which increases the resistance, making it harder to move the chairs position, but they will never lock.  This is a safety aspect of the chair design. ");
$faq['technical_amp_safety'][]=array("Which screwdriver do I need to fix my Lafuma chair and where can I get it?","The screwdriver to use is a T20 Torx head. It can be purchased online, or from places such as Halfords &amp; B&amp;Q.");
$faq['technical_amp_safety'][]=array("Where can I find details about furniture care?","Lafuma furniture is designed to last, however to ensure that the chair functions properly for 	the duration of its use, please click <a href='index.php?p=warranty'>here</a> to find out about care instructions.");
$faq['technical_amp_safety'][]=array("What safety specifications do the chairs meet?","Lafuma products are subject to uncompromising tests in our trial lab and either complies 	with European standard EN81 or are TUV and GS (Geprutte Sicherheit – German Testing) 	approved.  All padded &amp; Air Comfort products that are imported into the UK are also treated 	with fire retardant chemicals.");

$faq['guarantee'][]=array("How long is the Lafuma guarantee, and what does it cover?","Lafuma covers it products with a 2 year guarantee against faulty materials and workmanship.  This guarantee does not cover fair wear and tear, damage caused by misuse, or consumable parts like lacing cords.  The only exception to this rule is the clipper system on the Futura chairs, as these clips are guaranteed for 3 years.  For further information with regards to the Lafuma guarantee, please click <a href='index.php?p=warranty'>here</a>.");
$faq['guarantee'][]=array("My Lafuma product has developed a fault, what should I do?","If you purchased your chair from one of the Lafuma stockists (e.g. Go Outdoors or Dobbies) and the chair is within its 2 year guarantee; your first action should be to contact this stockist.  A contract of sale exists between you and the stockist, so the stockist is legally obliged to try and help.  You will need to provide proof of purchase in the way of a receipt, or possibly bank statement.  This is to prove that the chair is within its guarantee period.  If the chair is outside of its guarantee period, or if you have purchased the chair directly from us at www.lafuma.co.uk, then please read our Returns Policy  for full details of our returns procedure.");
$faq['guarantee'][]=array("Where can I find details about your Terms and Conditions of sale?","To read our full terms and conditions, please click here, or on the Terms and Conditions footer at the bottom of the page.  Please do read these Terms and Conditions before you commit to any purchase, as you will be subject to these in the event of purchase.");
$faq['guarantee'][]=array("I need to replace the lacing cords on my RSX chair; can they be replaced under the guarantee?","The lacing cords are considered a consumable part, and therefore not covered under the Lafuma guarantee.  Lacing cords can be purchased from many Lafuma stockists or directly from us by clicking <a href='index.php?p=products&pid=81&amp;prodname=lacing%20cords'>here</a>.");

$faq['payment_amp_delivery'][]=array("Can I pay by cheque?","We do allow payments by cheque; however this will slow down delivery as we will not be able to release the order until the cheque has cleared.  Please make all cheques payable to LLC Ltd.");
$faq['payment_amp_delivery'][]=array("Can I collect my order?","No, we do not allow customers to come and collect their orders directly from our address.");
$faq['payment_amp_delivery'][]=array("Do you have a showroom I can visit?","We do not have a showroom that is open to the public.  Our entire range is available to view 	online.   If you do wish to test a chair before you buy, you can find your local Lafuma stockist 	by clicking <a href='index.php?p=dealers'>here</a>.");
$faq['payment_amp_delivery'][]=array("What are my postage options, and what services can I opt for?","We offer a range of delivery options to suit all needs. The courier we use is Parcelforce, and the services that we offer are as follows: - <ul><li>Free Delivery (on orders over £50) (3-5 working days) - Free</li><li>Standard (2 working days) - &#163;4.95</li><li>Express (Next Day delivery) - &#163;7.95 (only for orders received by 12:00hrs)</li><li>Super Express (Pre 9am Next Day delivery) - &#163;14.95 (only for orders received by 12:00hrs)</li><li>Named day (specify a weekday to deliver) - &#163;7.95</li><li>Saturday Delivery - &#163;19.95</li><li>All deliveries to Ireland have a flat rate of &#8364;14.95</li></ul>
");
$faq['payment_amp_delivery'][]=array("How can I find my local Lafuma stockist?","Simply click on the tab <a href='index.php?p=dealers'>Local Stockists</a>, enter in your county, and you will get a list of stockists in your area.");

$faq['miscellaneous'][]=array("Where can I find details about your websites security?","Details on our website security can be found by clicking on either the <a href='index.php?p=privacy'>Privacy Policy</a> page or the <a href='index.php?p=buyguide'>Buying guide</a> page, both located in the footer.");
$faq['miscellaneous'][]=array("I am a retailer and I am interested in opening a trade account with you. How do I proceed?","The first step in the process is to click on the <a href='index.php?p=trade'>Trade Enquiry</a> tab. Fill out the form, and a member of the LLC Sales team will contact you in due course to discuss your requirements.");
$faq['miscellaneous'][]=array("Do you deal with Lafuma queries from customers outside of the UK &amp; Ireland?","No, we only deal with Lafuma customers based in the UK &amp; Ireland. You can find a list of all the distributors for Lafuma outside of the UK by clicking on the link <a href='https://www.lafuma.co.uk/lafumadistributors.pdf'>here</a>.");
$faq['miscellaneous'][]=array("I have seen quite a large range of chairs on www.lafuma.com; why don&acute;t you stock the entire range of Lafuma products?","www.lafuma.co.uk is owned and operated by LLC Ltd.  We are the sole importers and distributors of Lafuma for the UK & Ireland.  The Lafuma range is so vast that we only import a handful of products that are more tailored toward the needs of the UK & Irish market.");
$faq['miscellaneous'][]=array("A mouse has eaten my headrest!","This is fairly common!  Unfortunately, this is not covered by the guarantee, as it is not faulty workmanship or materials.  We do suggest that the chairs are kept in the <a href='index.php?p=products&amp;pid=59&amp;prodname=lafuma%20rsx%20bag'>Lafuma Carry Bag</a> when not in use to protect them from vermin.");
$faq['miscellaneous'][]=array("My question isn&acute;t listed here.  How do I contact you?","We can be contacted by email <a href='mailto:support@lafuma.co.uk'>support@lafuma.co.uk</a>, phone (01489 557600), fax (01489 	557705) or directly on this website by clicking on the <a href='index.php?p=contact'>Contact Us</a> tab and filling out the online form.");
?>
<h2 id="pagetitle">Frequently Asked Questions</h2>
<? foreach($faq as $title => $qas){foreach($qas as $id => $qa){?>
<a href="#anc_<?=$title."_".$id?>"><?=$qa[0]?></a><br />
<? }}?>

<? foreach($faq as $title => $qas){?>
<h3 style="text-decoration:underline;margin:10px 0 5px"><?=strtoupper(str_replace("_amp_"," &amp; ",$title))?></h3>
<? foreach($qas as $id => $qa){?>
<div class="faq_q1"><a name='anc_<?=$title."_".$id?>'></a>Q)</div><div class="faq_q2"><?=$qa[0]?></div>
<div class="clear"></div>
<div class="faq_a1">A)</div><div class="faq_a2"><?=$qa[1]?></div>
<div class="clear"></div>
<? }?>
<? }?>
